# This workflow will install node dependencies, build the source code and run the tests

name: CI

on:
  push:
    branches: [inspect]

jobs:
  test_render:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10 x64
        uses: actions/setup-node@v2
        with:
          node-version: 10
          architecture: x64
      - run: yarn install --frozen-lockfile
      - run: yarn run build-dev
      - run: xvfb-run -s "-ac -screen 0 1280x1024x24" yarn run test-render debug/overdraw
      - run: cat test/integration/render-tests/debug/overdraw/map.transform.json
