name: Delete Pull Request Demo

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    
    - name: Remove folder 
      run: git rm -rf ${{ github.event.number }}
    
    - name: Commit and push
      run: |
        git config --global user.name 'bot'
        git config --global user.email 'email@example.com'
        git commit -am "Remove ${{ github.event.number }}"
        git push

    - name: Add comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Live demo was deleted.
